# Assignment 3: Pandas
* Section: 02
* Name: Nate Yoon
* Due date: 2/21/21 @ noon
* Purpose: To understand the use of DataFrames while utilizing the Pandas library. 

## Problem 1: Calculate total amount

In [1]:
# Importing the essential libraries needed
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Declaring an array called Customer that includes five customers: April, Brian, Clara, Daniel, and Emily
Customer = np.array(['April', 'Brian', 'Clara', 'Daniel', 'Emily'])
Customer

array(['April', 'Brian', 'Clara', 'Daniel', 'Emily'], dtype='<U6')

In [55]:
# Using an integer random generator to produce an array named Quantity with five two digit integers.
# Using a seed of my choice.  
np.random.seed(0)
Quantity = np.random.randint(10,99,size=5)  # 1D array
Quantity

array([54, 57, 74, 77, 77])

In [56]:
# Generating an array using np.random.rand() with 5 values
# np.random.rand() is a function that creates an array of a specified shape and fills it with random values as per
# standard normal distribution
x1 = np.random.rand(5)
x1

array([0.84725174, 0.6235637 , 0.38438171, 0.29753461, 0.05671298])

In [57]:
# Multiplying the array (x1) by 10 to produce an array called Price.
y = 10 
Price = y*np.array(x1)
Price

array([8.47251739, 6.23563697, 3.84381707, 2.97534607, 0.56712977])

In [58]:
# Using the three arrays above to create a DataFrame called sales with the three columns: Customer, Quantity, and Price. 
sales =  pd.DataFrame({'Customer': Customer,'Quantity': Quantity,'Price': Price})
sales

Customer  Quantity     Price
0    April        54  8.472517
1    Brian        57  6.235637
2    Clara        74  3.843817
3   Daniel        77  2.975346
4    Emily        77  0.567130

In [59]:
# Calculating ExtendedAmount for each customer. ExtendedAmount is the product of Quantity and Price.  
ExtendedAmount= Quantity * Price
ExtendedAmount

array([457.51593894, 355.43130717, 284.4424634 , 229.10164704,
        43.66899253])

In [60]:
# Adding ExtendedAmount as a column to the sales Dataframe
sales['ExtendedAmount'] = pd.Series(ExtendedAmount)
sales

Customer  Quantity     Price  ExtendedAmount
0    April        54  8.472517      457.515939
1    Brian        57  6.235637      355.431307
2    Clara        74  3.843817      284.442463
3   Daniel        77  2.975346      229.101647
4    Emily        77  0.567130       43.668993

In [61]:
# Creating a function that calculates the discount for each customer based on the following discount rates:  
def discount(x):
    if x >= 500:
        return "20%"
    elif x >= 400:
        return "15%"
    elif x >= 200:
        return "10%"
    else:
        return"No discount"

In [62]:
# Applying the discount function to the ExtendedAmount column and add the discounts to a new column called Discounts
sales['Discounts'] = sales['ExtendedAmount'].apply(discount)
sales

Customer  Quantity     Price  ExtendedAmount    Discounts
0    April        54  8.472517      457.515939          15%
1    Brian        57  6.235637      355.431307          10%
2    Clara        74  3.843817      284.442463          10%
3   Daniel        77  2.975346      229.101647          10%
4    Emily        77  0.567130       43.668993  No discount

In [63]:
# Adding a new column called DiscountedAmount, subtracting Discounts from ExtendedAmount.
discounted_amount = []
for x in ExtendedAmount:
    if x >= 500:
        x = x * .8
    elif x >= 400:
        x = x * .85
    elif x >= 200:
        x = x * .9
    else:
        x = x 
    discounted_amount.append(x) # Adding x value to the discounted_amount array 

# Displaying final DataFrame
sales['DiscountedAmount'] = discounted_amount 
sales

Customer  Quantity     Price  ExtendedAmount    Discounts  DiscountedAmount
0    April        54  8.472517      457.515939          15%        388.888548
1    Brian        57  6.235637      355.431307          10%        319.888176
2    Clara        74  3.843817      284.442463          10%        255.998217
3   Daniel        77  2.975346      229.101647          10%        206.191482
4    Emily        77  0.567130       43.668993  No discount         43.668993

## Problem 2: Index and slice DataFrame

In [64]:
# How many columns and how many rows? 
# .shape command gives row count and column count (row count, column count)
sales.shape

(5, 6)

In [65]:
# What are the column names?  
# .columns command displays column names of the DataFrame
sales.columns

Index(['Customer', 'Quantity', 'Price', 'ExtendedAmount', 'Discounts',
       'DiscountedAmount'],
      dtype='object')

In [66]:
# How to retrieve the values of the DiscountedAmount column?
# [['x']] command retrieves values of specific column (x being column name)
sales[['DiscountedAmount']]

DiscountedAmount
0        388.888548
1        319.888176
2        255.998217
3        206.191482
4         43.668993

In [67]:
# Who purchases more 70 units?
sales[(sales['Quantity'] > 70)][['Customer', 'Quantity']]

Customer  Quantity
2    Clara        74
3   Daniel        77
4    Emily        77

In [68]:
# How much does Brian need to pay?  
sales[(sales['Customer'] == 'Brian')][['Customer','DiscountedAmount']]

Customer  DiscountedAmount
1    Brian        319.888176