# Assignment 2: NumPy

* Section: 02
* Name: Nate Yoon
* Due date: 2/13/21 @ noon
* Purpose: Assignment 2 is to enhance our knowledge in slicing, declaring, and indexing numpy arrays. Also, this assignment allowed us to define functions, use if statements, and calculate various problems using the python language.

In [1]:
# Importing the 4 essential libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Problem 1: Slicing and Indexing a NumPy Array

In [2]:
# Setting a random seed at 100 and creating a matrix of 6 rows by 6 columns with values between 10 and 99(inclusively)  
np.random.seed(100)
x2 = np.random.randint(low=10, high=100, size=(6, 6))  # 2D array
x2

array([[18, 34, 77, 97, 89, 58],
       [20, 62, 63, 76, 24, 44],
       [34, 25, 70, 68, 26, 19],
       [96, 12, 37, 14, 41, 11],
       [23, 93, 14, 69, 77, 17],
       [59, 57, 75, 71, 24, 65]])

In [3]:
# Retrieving values at the third row
x2[2]

array([34, 25, 70, 68, 26, 19])

In [4]:
# Retrieving values at the fourth column
x2[:,3]

array([97, 76, 68, 14, 69, 71])

In [5]:
# Retrieving values at even rows
x2[::2]

array([[18, 34, 77, 97, 89, 58],
       [34, 25, 70, 68, 26, 19],
       [23, 93, 14, 69, 77, 17]])

In [6]:
# Retrieving values at first, and fourth columns
x2[:,[0,3]]

array([[18, 97],
       [20, 76],
       [34, 68],
       [96, 14],
       [23, 69],
       [59, 71]])

In [7]:
# Retrieving values at second, third, fourth, fifth and sixth rows, and at third, fourth and fifth columns
x2[1:6,[2,3,4]]

array([[63, 76, 24],
       [70, 68, 26],
       [37, 14, 41],
       [14, 69, 77],
       [75, 71, 24]])

## Problem 2: Calculate total amount

In [8]:
# Declaring an array called Customer that includes five customers: April, Brian, Clara, Daniel, and Emily
Customer = np.array(['April', 'Brian', 'Clara', 'Daniel', 'Emily'])
Customer

array(['April', 'Brian', 'Clara', 'Daniel', 'Emily'], dtype='<U6')

In [9]:
# Using an integer random generator to produce an array named Quantity with five integers between 70 and 99. 
# Using a seed of my choice.  
np.random.seed(0)
Quantity = np.random.randint(70,99,size=5)  # 1D array
Quantity

array([82, 85, 91, 70, 73])

In [10]:
# Generating an array using np.random.rand() with 5 values
# np.random.rand() is a function that creates an array of a specified shape and fills it with random values as per
# standard normal distribution
x1 = np.random.rand(5)
x1

array([0.85794562, 0.84725174, 0.6235637 , 0.38438171, 0.29753461])

In [11]:
# Multiply the array (x1) by 10 to produce an array called Price.
y = 10 
Price = y*np.array(x1)
Price

array([8.57945618, 8.47251739, 6.23563697, 3.84381707, 2.97534607])

In [12]:
# Calculating ExtendedAmount for each customer. ExtendedAmount is the product of Quantity and Price.  
ExtendedAmount= Quantity * Price
ExtendedAmount

array([703.51540645, 720.16397797, 567.44296408, 269.0671951 ,
       217.20026278])

In [13]:
# Creating a function that calculates the discount for each customer based on the following discount rates:  
def discount(x):
    if x >= 500:
        return "Discount is 20%"
    elif 400 <= x <= 500:
        return "Discount is 15%"
    elif 200 <= x <=400:
        return "Discount is 10%"
    else:
        return"Discount is 0%"

np.array(list(map(discount,ExtendedAmount)))

array(['Discount is 20%', 'Discount is 20%', 'Discount is 20%',
       'Discount is 10%', 'Discount is 10%'], dtype='<U15')

In [14]:
# Printing out each customer name, extended amount, discount and final price.
# Separating each customer’s data with a line, using “‐‐‐” or “===” 
print("Customer Name:", Customer[0], ",", "ExtendedAmount:", ExtendedAmount[0], ",", 
np.array(list(map(discount,ExtendedAmount)))[0], "," , "Final Price:", ExtendedAmount[0]-(ExtendedAmount[0]*.20))
print("------------------------------------------------------------------------------------------------------------")
print("Customer Name:", Customer[1], ",", "ExtendedAmount:", ExtendedAmount[1], ",", 
np.array(list(map(discount,ExtendedAmount)))[1], "," , "Final Price:", ExtendedAmount[1]-(ExtendedAmount[1]*.20))
print("------------------------------------------------------------------------------------------------------------")
print("Customer Name:", Customer[2], ",", "ExtendedAmount:", ExtendedAmount[2], ",", 
np.array(list(map(discount,ExtendedAmount)))[2], "," , "Final Price:", ExtendedAmount[2]-(ExtendedAmount[2]*.20))
print("------------------------------------------------------------------------------------------------------------")
print("Customer Name:", Customer[3], ",", "ExtendedAmount:", ExtendedAmount[3], ",", 
np.array(list(map(discount,ExtendedAmount)))[3], "," , "Final Price:", ExtendedAmount[3]-(ExtendedAmount[3]*.10))
print("------------------------------------------------------------------------------------------------------------")
print("Customer Name:", Customer[4], ",", "ExtendedAmount:", ExtendedAmount[4], ",", 
np.array(list(map(discount,ExtendedAmount)))[4], "," , "Final Price:", ExtendedAmount[4]-(ExtendedAmount[4]*.10))

Customer Name: April , ExtendedAmount: 703.5154064506606 , Discount is 20% , Final Price: 562.8123251605285
------------------------------------------------------------------------------------------------------------
Customer Name: Brian , ExtendedAmount: 720.1639779665066 , Discount is 20% , Final Price: 576.1311823732053
------------------------------------------------------------------------------------------------------------
Customer Name: Clara , ExtendedAmount: 567.4429640752348 , Discount is 20% , Final Price: 453.9543712601879
------------------------------------------------------------------------------------------------------------
Customer Name: Daniel , ExtendedAmount: 269.0671951048899 , Discount is 10% , Final Price: 242.1604755944009
------------------------------------------------------------------------------------------------------------
Customer Name: Emily , ExtendedAmount: 217.20026277746476 , Discount is 10% , Final Price: 195.48023649971827
